name: RengieMendoza
favicon: null
layout_spectrum: 0.99202
typography_spectrum: 0.43138
title: RenzaGroup
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202728'
    - '#ffffff'
    - '#d40000'
    - '#e97f7f'
    - '#84898a'
  brandStrength: 0.725112964399159
  lightness: 0.1944160230923444
  saturation: 0.06954264407977462
  rhythmicContrast: 0.44540930329822004
purpose: []
