name: RengieMendoza
favicon: null
layout_spectrum: 0.7474
typography_spectrum: 0.43138
title: RenzaGroup
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202728'
    - '#ffffff'
    - '#d40000'
    - '#e97f7f'
    - '#84898a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
